stages:
  - 📦 build
  - 🤞 test
  - 🦄 quality
  - 🚀 deploy

pages:
  stage: 🚀 deploy
  script:
    - mkdir .public
    - mv docs/build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master